saude:
    resource: "@SaudeBundle/Controller/"
    type:     annotation
    prefix:   /

security:
    resource: "@SerBinarioSecurityBundle/Controller/"
    type:     annotation
    prefix:   /security

