root:
    path: /
    defaults:
        _controller: FrameworkBundle:Redirect:urlRedirect
        path: /home
        permanent: true

saude:
    resource: "@SaudeBundle/Controller/"
    type:     annotation
    prefix:   /

security:
    resource: "@SerBinarioSecurityBundle/Controller/"
    type:     annotation
    prefix:   /security

