security:    
    encoders:
        Serbinario\Bundle\SecurityBundle\Entity\User:
            algorithm: bcrypt
            
    providers:
        our_db_provider:
            entity:
                class: SerBinarioSecurityBundle:User
                #property: username
                    
    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            provider: our_db_provider
            remember_me:
                key:      "%secret%"
                lifetime: 604800 # 1 week in seconds
                path:     /home
            anonymous: ~
            form_login:
                login_path: /security/login
                check_path: /security/login_check                
            logout:
                path:   /security/logout
                target: /home
        
    access_control:
        # require ROLE_ADMIN for /admin*
        - { path: ^/security/login , roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/security/login_check , roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/*, roles: ROLE_USER }
        

