AgendaMedico:
    type: entity
    table: agenda_medico
    indexes:
        fk_agenda_medico_tipo_agenda1_idx:
            columns:
                - tipo_agenda_id_tipo_agenda
        fk_agenda_medico_medico1_idx:
            columns:
                - medico_id_medico
    id:
        idAgendaMedico:
            type: integer
            nullable: false
            unsigned: false
            comment: ''
            id: true
            column: id_agenda_medico
            generator:
                strategy: IDENTITY
    manyToOne:
        medicoMedico:
            targetEntity: Medico
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                medico_id_medico:
                    referencedColumnName: id_medico
            orphanRemoval: false
        tipoAgendaTipoAgenda:
            targetEntity: TipoAgenda
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                tipo_agenda_id_tipo_agenda:
                    referencedColumnName: id_tipo_agenda
            orphanRemoval: false
    lifecycleCallbacks: {  }
