DiasCalendario:
    type: entity
    table: dias_calendario
    id:
        idDiasCalendario:
            type: integer
            nullable: false
            unsigned: false
            comment: ''
            id: true
            column: id_dias_calendario
            generator:
                strategy: IDENTITY
    fields:
        nomeDiasCalendario:
            type: string
            nullable: false
            length: 45
            fixed: false
            comment: ''
            column: nome_dias_calendario
    lifecycleCallbacks: {  }
