Especialidade:
    type: entity
    table: especialidade
    id:
        idEspecialidade:
            type: integer
            nullable: false
            unsigned: false
            comment: ''
            id: true
            column: id_especialidade
            generator:
                strategy: IDENTITY
    fields:
        nomeEspecialidade:
            type: string
            nullable: false
            length: 50
            fixed: false
            comment: ''
            column: nome_especialidade
    lifecycleCallbacks: {  }
