Eventos:
    type: entity
    table: eventos
    indexes:
        fk_eventos_agendamento1_idx:
            columns:
                - id_agendamento
    id:
        idEventos:
            type: integer
            nullable: false
            unsigned: false
            comment: ''
            id: true
            column: id_eventos
            generator:
                strategy: IDENTITY
    fields:
        title:
            type: string
            nullable: true
            length: 100
            fixed: false
            comment: ''
        start:
            type: datetime
            nullable: true
            comment: ''
        end:
            type: datetime
            nullable: true
            comment: ''
    manyToOne:
        idAgendamento:
            targetEntity: Agendamento
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                id_agendamento:
                    referencedColumnName: id_agendamento
            orphanRemoval: false
    lifecycleCallbacks: {  }
