Localidade:
    type: entity
    table: localidade
    id:
        idLocalidade:
            type: integer
            nullable: false
            unsigned: false
            comment: ''
            id: true
            column: id_localidade
            generator:
                strategy: IDENTITY
    fields:
        nomeLocalidade:
            type: string
            nullable: false
            length: 45
            fixed: false
            comment: ''
            column: nome_localidade
    lifecycleCallbacks: {  }
