Paciente:
    type: entity
    table: paciente
    id:
        idPaciente:
            type: integer
            nullable: false
            unsigned: false
            comment: ''
            id: true
            column: id_paciente
            generator:
                strategy: IDENTITY
    fields:
        nomePaciente:
            type: string
            nullable: false
            length: 45
            fixed: false
            comment: ''
            column: nome_paciente
    lifecycleCallbacks: {  }
