Reagendamento:
    type: entity
    table: reagendamento
    indexes:
        fk_reagendamento_consulta1_idx:
            columns:
                - consulta_id_consulta_adiado
        fk_reagendamento_consulta2_idx:
            columns:
                - consulta_id_consulta_remarcado
    id:
        idReagendamento:
            type: integer
            nullable: false
            unsigned: false
            comment: ''
            id: true
            column: id_reagendamento
            generator:
                strategy: IDENTITY
    fields:
        observacaoReagendamento:
            type: text
            nullable: false
            length: null
            fixed: false
            comment: ''
            column: observacao_reagendamento
    manyToOne:
        consultaConsultaAdiado:
            targetEntity: Agendamento
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                consulta_id_consulta_adiado:
                    referencedColumnName: id_agendamento
            orphanRemoval: false
        consultaConsultaRemarcado:
            targetEntity: Agendamento
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                consulta_id_consulta_remarcado:
                    referencedColumnName: id_agendamento
            orphanRemoval: false
    lifecycleCallbacks: {  }
